---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

I have learned the importance of practicing writing out tidy codes that are easy to read and understandable. For example, I learned how to break up codes into different lines after a comma or a plus sign. I realize that just having the correct codes is not enough for a data scientist to succeed in his career as the interaction between readers and the data scientists are also very important in the field of data science. Therefore, having codes that are tidy and organized will make the readers easy to understand what you are doing with your projects. For example, in lab 9 section 3: question 3 I end the line when there is a pipe operator, a comma, or a plus sign. Another important aspect of my growth as a data scientists is to learn how to do the proper research. For example, when I do research for writing codes for my project, I will try to look at the dates the articles were posted so I could make sure the information are not outdated. I will also try to use the help file inside R studio to know if the function that I was looking for online has been superseded. For example in challenge 9 question 10 table I use the ungroup function to have the percentage sign be displayed on the table and I know that this function is not outdated and is continued to be used based on my research. I also learned through lectures about the important differences of each data type and why we sometimes we need to convert into another data type in order for our codes to work. For example, in lab 3 question 5 I used the mutate functions to change the data types of my variables from either numeric or characters to factors so that I will not encounter any troubles of reading in the wrong information when I continue to write my codes. I also learned about the importance of designing either the tables or graphs of your output. Previously, when I have not taken this class, I thought that the design of either your graph or tables is not that important as the readers only care about whether you have the right information or not. However, this class taught me that being a data scientists also means that outputting the right information as clear as possible should be the ultimate goal and having good design of your graph or table is one aspect of that. For example, in challenge 9 question 9 and 10 tables I added a border line that separates the values of the variable State from the three variables representing the three different types of spelling of "Allan" so that the readers would know that the main focus of the tables should be on the frequencies or percentages of the three different types of spelling of "Allan " in each of these two states.
