---
title: "The Power of Efficiency"
format: html
editor: visual
---

Efficiency in statistical computing is about typing out codes without using repeating functions. For example, if you want to filter several variables in your dataset, you could use the filter function once by putting several variables inside the filter function and separate them by commas. The main idea of efficiency in data science is to complete a project by typing out as few codes as possible but with the correct syntax and functions. For example, you would not want to create a new dataset just for creating a graph using ggplot. Instead, you could use the pipe operator from the dplyr package to pipe the codes you have type directly into the ggplot. Efficiency makes me realize that I have not type out codes the way it should be in my previous coding course. When I was taking Stat 330, I have multiple times use repeated codes to get the desired results for my assignments and at that time, I only care about the results but not the process. Even though I could use repeated codes to get the right answers in Stat 330, I have found out that other students are able to complete their assignments faster than me. After taking this course, I have realize that efficiency is very important as Professor has told us we should not have too much lines for our codes and repeated functions are unnecessary. One important aspect of efficiency is the relationship between the readers and the data scientists. You want your codes to be "interesting" so the readers could learn from your examples and repeated codes are generally "boring" which will cause the readers to become uninterested in reading your codes. Having efficient codes are important because you want to demonstrate to others that you are skilled in the computing languages and other could trust you for carrying out data analysis. I found out that through this course you could complete more computing tasks or assignments within a certain time period if you do not waste too much time typing out repeated codes to achieve a certain result. For example, initially, on lab 9 section 3 question 1 I wanted to use another function to fill all the NA's with 0 but Professor suggested me to do both pivoting and filling with 0 within a single function. Eventually, I used the values_fill option within pivot_wider to fill all the NA's with zero. On lab 7 question 3.1, I have initially not use the range function to carry out the rescaling function. However, after looking through Professor's comment about my function, I found out that is repetitive so I have eventually learned about the importance of the range function.
